version: '3.5'

services:
  db:
    image: mysql:latest
    restart: always
    container_name: mysql-container
    environment:
      MYSQL_USER: 'maria'
      MYSQL_PASSWORD: 'admin123'
      MYSQL_DATABASE: 'daily-diet'
      MYSQL_ROOT_PASSWORD: 'admin1234'
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: